# Generated by Django 2.0.3 on 2018-03-14 01:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('hours', '0001_initial'),
        ('dogs', '0002_dog_owner'),
        ('walkers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place', models.IntegerField(default=3)),
                ('dog', models.ManyToManyField(related_name='walk', to='dogs.Dog')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk', to='hours.Hour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk', to='owners.Owner')),
                ('walker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk', to='walkers.Walker')),
            ],
        ),
    ]
