# Generated by Django 2.0.3 on 2018-03-10 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour_available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end', to='walkers.Hour_available')),
                ('start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='walkers.Hour_available')),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='walk',
            name='walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk', to='walkers.Walker'),
        ),
        migrations.AddField(
            model_name='hour_available',
            name='walkers',
            field=models.ManyToManyField(blank=True, to='walkers.Walker'),
        ),
    ]
