# Generated by Django 2.0.3 on 2018-03-14 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hour', models.ManyToManyField(related_name='walker', to='hours.Hour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='walker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
